### ISSUE TITLE
there is a little problem on new incoming messages

### ISSUE THREAD

**Issue by hueldoeu** [redsolution/xabber-server#12]
i like to write from miranda ng on windows 10 to my lg g5 android 8 all updates with xabber newest version from playstore.

i write a message like "hello" from windows to xabber. it appears a popup on my smartphone. i click on this popup and see the message. now i want to copy the message and paste it e. g. in my calender. now imagine it good:

i click on the message so that a context menu appers. the context has "quote, copy, delete". i want to press EDIT   !!!

this is the problem: the context menu jumps a few centimeters higher. this is very disgusting because this way i press DELETE accidently.

it only happens once. i can test it again. i don't close xabber. i send a message to xabber. i click on the popup. at the bottom of the screen i see my message. i click on it NOW. hmm it's ok. now i close xabber really. i will exit it. i will restart it.

i send a message to xabber. i click on the popup. at the bottom of the screen i see my message. i click on it NOW to see the context menu. HA! the context menu falls down, this time it is lower. i would have clicked QUOTE accidently.

usually i must wait a few seconds, or i click somewhere else on the screen and press the message again.

btw clicking and opening links in messages is easy but it i want to copy the message or open the context menu, i really have to click carefully. far away from the message. otherwise the link opens.

small links are easy if you want to open the context menu. but clicking the link this time is hard because its so small.

please help.

**Comment by andrewnenakhov** [comment]
1. This is a tracker for server issues. You clearly have a client issue. 
2. Latest version of client allows you to longpress on the message, select one or several mesages and copy them at once. Hope that helps.

**Comment by hueldoeu** [comment]
1. sry
2. yes the long press is fine too, i can choose copy at the bottom of the page but with short press context menu i can save a bit time. so where is the client issues forum?

i mean, with this bug, xabber is a bit buggy. that's what i meant. it's a bug. i can live with it by spending a bit time but the short press context menu jumps the first time it has opened.

**Comment by andrewnenakhov** [comment]
It doesn't jump for us. Also, it is hard to understand what's happening from your description. Android issues can be posted at https://github.com/redsolution/xabber-android/

**Comment by hueldoeu** [comment]
all in all xabber is really perfect. i use it since it's on playstore. keep it up!

**Comment by andrewnenakhov** [comment]
@hueldoeu can you make a video with how it is jumping and put it to dropbox or whatever and show it to us?

**Comment by hueldoeu** [comment]
which recording software do you recommend. i could post it on youtube.

**Comment by andrewnenakhov** [comment]
@hueldoeu any would do. AZrecorder or anything.

**Comment by hueldoeu** [comment]
https://jabber.de:5281/upload/yPntu-iB_y0Oa1XR/Neues%20Video.mp4

**Comment by hueldoeu** [comment]
the 10 last seconds shows it the best.

**Comment by hueldoeu** [comment]
sending photos, videos and other files through secured xmpp are, if the server has been set up easily and works good and is free, the best present a human can do for me. thank you sir.

**Comment by hueldoeu** [comment]
i found out it's because of the energy savings. i don't need extra 3D animations and i prefer long battery life time so i activated battery saving mode (don't know the correct translation). my gps is broken, typical problem of lg g5 because it doesn't have contact with the gps antenna. i thought deactivating battery save mode will correct the gps problem but it seems i have to open the smartphone again. however i noticed that the jumping doesn't happen anymore. thread can be closed now.

i still have an LG G5 850 whatever.

**Comment by hueldoeu** [comment]
i have to corrent: i happened right now again.
