### ISSUE TITLE
Relicensing

### ISSUE THREAD

**Issue by licaon-kter** [redsolution/xabber-server#2]
From [blog post](https://blog.xabber.com/xabber-server-v-0-9-alpha-is-released/amp/):
> We are extremely grateful to ProcessOne team for creating world's best XMPP server, this release wouldn't be possible without your hard work

Then you turn around and [you relicense](https://github.com/redsolution/xabber-server/blob/master/COPYING) your work and theirs.

One could name this as a _"d*ck move"_, you build it on **their** work yet now you block ProcessOne from backporting **your** work.

Why?

/PS: I understand what Affero brings, not sure what you bring for ejabberd in the future, unless you'd want to be a server developer from now on too

**Comment by andrewnenakhov** [comment]
Well, folks, this is open-source at its finest: you spend years and tons of money to bring something forth for the community, then some wise person comes and starts ranting how you did a "d*ck move".  Sad!

We respect license obligations imposed by ProcessOne on their code. Files, linked with original ejabberd code remain under GNU GPL v2 license, as they should be. ProcessOne is free to backport our code to their server. 

However, Xabber Server consists of much more components than just modified ejabberd. Those components were created by us and we license our code as we see fit. Just as ProcessOne licensed their code as they saw fit.
