### ISSUE TITLE
xabberserver.service instantly being stopped

### ISSUE THREAD

**Issue by ignatif** [redsolution/xabber-server#9]
<img width="1057" alt="Screenshot 2020-07-26 at 20 24 44" src="https://user-images.githubusercontent.com/15590185/88485426-3ded1d00-cf7e-11ea-8bbb-31996e3292f3.png">

I successfully installed the server but it's being shutted down instantly.

```bash
$ sudo service apache2 restart
$ sudo systemctl status xabberserver.service
● xabberserver.service - Xabber Server
   Loaded: loaded (/etc/systemd/system/xabberserver.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sun 2020-07-26 17:23:06 UTC; 1min 3s ago
  Process: 11530 ExecStop=/opt/xabberserver/xabberserver/xmppserverui/xabber-server stop (code=exited, status=0/SUCCESS)
  Process: 11509 ExecStart=/opt/xabberserver/xabberserver/xmppserverui/xabber-server start (code=exited, status=0/SUCCESS)
 Main PID: 11509 (code=exited, status=0/SUCCESS)

Jul 26 17:23:04 ip-172-31-55-107 systemd[1]: Started Xabber Server.
Jul 26 17:23:06 ip-172-31-55-107 xabber-server[11530]: Xabber Server is stopped
```

Do you know what might be the problem? how can i check logs?

**Comment by Sternstein** [comment]
Thank you for your issue ticket. It seems that installation missed file for WebUI configuration.
To setup Xabber Server UI component you need to add and change file /etc/xabber/xabber_server.ini

[panel]

ip = 0.0.0.0

port = 8000

daemon = no

pid_file = /opt/xabberserver/xabberserver/xabber_server.pid

workers = 3

debug = no

log_dir =

**Comment by ignatif** [comment]
thank you @Sternstein that helped

could you please also help me on this issue: https://github.com/redsolution/xabber-websocket/issues/7? last thing blocking me from trying your server, quite exited
